/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyUsageResponse {
    #[serde(rename = "keys")]
    pub keys: Vec<models::ApiKeyUsageDetail>,
    #[serde(rename = "periodEnd")]
    pub period_end: String,
    #[serde(rename = "periodStart")]
    pub period_start: String,
}

impl ApiKeyUsageResponse {
    pub fn new(keys: Vec<models::ApiKeyUsageDetail>, period_end: String, period_start: String) -> ApiKeyUsageResponse {
        ApiKeyUsageResponse {
            keys,
            period_end,
            period_start,
        }
    }
}

