/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyUsageDetail {
    #[serde(rename = "apiKeyId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_key_id: Option<Option<String>>,
    #[serde(rename = "currentPeriod")]
    pub current_period: Box<models::CaptureUsageCounts>,
    #[serde(rename = "keyPrefix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub key_prefix: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "totals")]
    pub totals: Box<models::CaptureUsageCounts>,
}

impl ApiKeyUsageDetail {
    pub fn new(current_period: models::CaptureUsageCounts, name: String, totals: models::CaptureUsageCounts) -> ApiKeyUsageDetail {
        ApiKeyUsageDetail {
            api_key_id: None,
            current_period: Box::new(current_period),
            key_prefix: None,
            name,
            totals: Box::new(totals),
        }
    }
}

