/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BandwidthQuotaResponse {
    #[serde(rename = "limitBytes")]
    pub limit_bytes: i64,
    #[serde(rename = "limitFormatted")]
    pub limit_formatted: String,
    #[serde(rename = "percentUsed")]
    pub percent_used: i32,
    #[serde(rename = "remainingBytes")]
    pub remaining_bytes: i64,
    #[serde(rename = "remainingFormatted")]
    pub remaining_formatted: String,
    #[serde(rename = "usedBytes")]
    pub used_bytes: i64,
    #[serde(rename = "usedFormatted")]
    pub used_formatted: String,
}

impl BandwidthQuotaResponse {
    pub fn new(limit_bytes: i64, limit_formatted: String, percent_used: i32, remaining_bytes: i64, remaining_formatted: String, used_bytes: i64, used_formatted: String) -> BandwidthQuotaResponse {
        BandwidthQuotaResponse {
            limit_bytes,
            limit_formatted,
            percent_used,
            remaining_bytes,
            remaining_formatted,
            used_bytes,
            used_formatted,
        }
    }
}

