/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BorderConfig {
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "radius", skip_serializing_if = "Option::is_none")]
    pub radius: Option<i32>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl BorderConfig {
    pub fn new() -> BorderConfig {
        BorderConfig {
            color: None,
            radius: None,
            width: None,
        }
    }
}

