/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowserSessionRequest {
    #[serde(rename = "cookies", skip_serializing_if = "Option::is_none")]
    pub cookies: Option<Vec<models::BrowserCookieRequest>>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<models::BrowserHeaderRequest>>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Vec<models::BrowserStorageOriginRequest>>,
}

impl BrowserSessionRequest {
    pub fn new() -> BrowserSessionRequest {
        BrowserSessionRequest {
            cookies: None,
            headers: None,
            storage: None,
        }
    }
}

