/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowserStorageOriginRequest {
    #[serde(rename = "localStorage", skip_serializing_if = "Option::is_none")]
    pub local_storage: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "origin")]
    pub origin: String,
    #[serde(rename = "sessionStorage", skip_serializing_if = "Option::is_none")]
    pub session_storage: Option<std::collections::HashMap<String, String>>,
}

impl BrowserStorageOriginRequest {
    pub fn new(origin: String) -> BrowserStorageOriginRequest {
        BrowserStorageOriginRequest {
            local_storage: None,
            origin,
            session_storage: None,
        }
    }
}

