/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowserCookieRequest {
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    #[serde(rename = "expires", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires: Option<Option<f64>>,
    #[serde(rename = "httpOnly", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub http_only: Option<Option<bool>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "sameSite", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub same_site: Option<Option<String>>,
    #[serde(rename = "secure", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secure: Option<Option<bool>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl BrowserCookieRequest {
    pub fn new(name: String) -> BrowserCookieRequest {
        BrowserCookieRequest {
            domain: None,
            expires: None,
            http_only: None,
            name,
            path: None,
            same_site: None,
            secure: None,
            value: None,
        }
    }
}

