/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkJobInfo {
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "resultUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_url: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl BulkJobInfo {
    pub fn new(id: String, status: String, url: String) -> BulkJobInfo {
        BulkJobInfo {
            error_code: None,
            error_message: None,
            id,
            result_url: None,
            status,
            url,
        }
    }
}

