/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkJobDetailInfo {
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "fileSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<Option<i64>>,
    #[serde(rename = "format", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub format: Option<Option<String>>,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<i32>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "renderTimeMs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub render_time_ms: Option<Option<i64>>,
    #[serde(rename = "resultUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_url: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "storageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_url: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<i32>>,
}

impl BulkJobDetailInfo {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, status: String, url: String) -> BulkJobDetailInfo {
        BulkJobDetailInfo {
            completed_at: None,
            created_at,
            error_code: None,
            error_message: None,
            file_size: None,
            format: None,
            height: None,
            id,
            render_time_ms: None,
            result_url: None,
            status,
            storage_url: None,
            url,
            width: None,
        }
    }
}

