/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkDefaults {
    #[serde(rename = "actions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Option<Vec<models::PageAction>>>,
    #[serde(rename = "blockAds", skip_serializing_if = "Option::is_none")]
    pub block_ads: Option<bool>,
    #[serde(rename = "blockCookieBanners", skip_serializing_if = "Option::is_none")]
    pub block_cookie_banners: Option<bool>,
    #[serde(rename = "blockLevel", skip_serializing_if = "Option::is_none")]
    pub block_level: Option<String>,
    #[serde(rename = "blockPopups", skip_serializing_if = "Option::is_none")]
    pub block_popups: Option<bool>,
    #[serde(rename = "customCss", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_css: Option<Option<String>>,
    #[serde(rename = "darkMode", skip_serializing_if = "Option::is_none")]
    pub dark_mode: Option<bool>,
    #[serde(rename = "delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<i32>,
    #[serde(rename = "device", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device: Option<Option<String>>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "fullPage", skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    #[serde(rename = "outputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Option<Vec<models::OutputSpec>>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<i32>,
    #[serde(rename = "stealthMode", skip_serializing_if = "Option::is_none")]
    pub stealth_mode: Option<bool>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
    #[serde(rename = "viewport", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub viewport: Option<Option<Box<models::ViewportConfig>>>,
    #[serde(rename = "waitFor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wait_for: Option<Option<String>>,
    #[serde(rename = "waitUntil", skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<String>,
}

impl BulkDefaults {
    pub fn new() -> BulkDefaults {
        BulkDefaults {
            actions: None,
            block_ads: None,
            block_cookie_banners: None,
            block_level: None,
            block_popups: None,
            custom_css: None,
            dark_mode: None,
            delay: None,
            device: None,
            format: None,
            full_page: None,
            outputs: None,
            quality: None,
            stealth_mode: None,
            timeout: None,
            viewport: None,
            wait_for: None,
            wait_until: None,
        }
    }
}

