/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkRequest {
    #[serde(rename = "defaults", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub defaults: Option<Option<Box<models::BulkDefaults>>>,
    #[serde(rename = "urls")]
    pub urls: Vec<models::BulkUrlRequest>,
    #[serde(rename = "webhookSecret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
    #[serde(rename = "webhookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
}

impl BulkRequest {
    pub fn new(urls: Vec<models::BulkUrlRequest>) -> BulkRequest {
        BulkRequest {
            defaults: None,
            urls,
            webhook_secret: None,
            webhook_url: None,
        }
    }
}

