/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkStatusResponse {
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "completedJobs")]
    pub completed_jobs: i32,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "failedJobs")]
    pub failed_jobs: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::BulkJobDetailInfo>,
    #[serde(rename = "progress")]
    pub progress: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "totalJobs")]
    pub total_jobs: i32,
}

impl BulkStatusResponse {
    pub fn new(completed_jobs: i32, created_at: chrono::DateTime<chrono::FixedOffset>, failed_jobs: i32, id: String, jobs: Vec<models::BulkJobDetailInfo>, progress: i32, status: String, total_jobs: i32) -> BulkStatusResponse {
        BulkStatusResponse {
            completed_at: None,
            completed_jobs,
            created_at,
            failed_jobs,
            id,
            jobs,
            progress,
            status,
            total_jobs,
        }
    }
}

