/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaptureInfo {
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "originalHeight")]
    pub original_height: i32,
    #[serde(rename = "originalWidth")]
    pub original_width: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "width")]
    pub width: i32,
    #[serde(rename = "x")]
    pub x: i32,
    #[serde(rename = "y")]
    pub y: i32,
}

impl CaptureInfo {
    pub fn new(height: i32, id: String, original_height: i32, original_width: i32, url: String, width: i32, x: i32, y: i32) -> CaptureInfo {
        CaptureInfo {
            height,
            id,
            label: None,
            original_height,
            original_width,
            url,
            width,
            x,
            y,
        }
    }
}

