/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaptureUsageCounts {
    #[serde(rename = "bandwidthBytes")]
    pub bandwidth_bytes: i64,
    #[serde(rename = "screenshotsCount")]
    pub screenshots_count: i64,
}

impl CaptureUsageCounts {
    pub fn new(bandwidth_bytes: i64, screenshots_count: i64) -> CaptureUsageCounts {
        CaptureUsageCounts {
            bandwidth_bytes,
            screenshots_count,
        }
    }
}

