/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaptureItem {
    #[serde(rename = "darkMode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dark_mode: Option<Option<bool>>,
    #[serde(rename = "delay", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delay: Option<Option<i32>>,
    #[serde(rename = "device", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device: Option<Option<String>>,
    #[serde(rename = "fullPage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub full_page: Option<Option<bool>>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "viewport", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub viewport: Option<Option<Box<models::ViewportConfig>>>,
}

impl CaptureItem {
    pub fn new(url: String) -> CaptureItem {
        CaptureItem {
            dark_mode: None,
            delay: None,
            device: None,
            full_page: None,
            id: None,
            label: None,
            url,
            viewport: None,
        }
    }
}

