/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeResponse {
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "fileSize")]
    pub file_size: i64,
    #[serde(rename = "format")]
    pub format: String,
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "layout")]
    pub layout: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::ComposeMetadata>,
    #[serde(rename = "renderTimeMs")]
    pub render_time_ms: i64,
    #[serde(rename = "storageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_url: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "width")]
    pub width: i32,
}

impl ComposeResponse {
    pub fn new(expires_at: chrono::DateTime<chrono::FixedOffset>, file_size: i64, format: String, height: i32, layout: String, metadata: models::ComposeMetadata, render_time_ms: i64, url: String, width: i32) -> ComposeResponse {
        ComposeResponse {
            expires_at,
            file_size,
            format,
            height,
            layout,
            metadata: Box::new(metadata),
            render_time_ms,
            storage_url: None,
            url,
            width,
        }
    }
}

