/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeRequest {
    #[serde(rename = "async", skip_serializing_if = "Option::is_none")]
    pub r#async: Option<bool>,
    #[serde(rename = "captures", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub captures: Option<Option<Vec<models::CaptureItem>>>,
    #[serde(rename = "capturesMode", skip_serializing_if = "Option::is_none")]
    pub captures_mode: Option<bool>,
    #[serde(rename = "defaults", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub defaults: Option<Option<Box<models::CaptureDefaults>>>,
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<Box<models::ComposeOutputConfig>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "variants", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variants: Option<Option<Vec<models::VariantConfig>>>,
    #[serde(rename = "variantsMode", skip_serializing_if = "Option::is_none")]
    pub variants_mode: Option<bool>,
    #[serde(rename = "webhookSecret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
    #[serde(rename = "webhookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
}

impl ComposeRequest {
    pub fn new() -> ComposeRequest {
        ComposeRequest {
            r#async: None,
            captures: None,
            captures_mode: None,
            defaults: None,
            output: None,
            url: None,
            variants: None,
            variants_mode: None,
            webhook_secret: None,
            webhook_url: None,
        }
    }
}

