/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeMetadata {
    #[serde(rename = "canvasHeight")]
    pub canvas_height: i32,
    #[serde(rename = "canvasWidth")]
    pub canvas_width: i32,
    #[serde(rename = "captures")]
    pub captures: Vec<models::CaptureInfo>,
    #[serde(rename = "layoutType")]
    pub layout_type: String,
    #[serde(rename = "totalCaptures")]
    pub total_captures: i32,
}

impl ComposeMetadata {
    pub fn new(canvas_height: i32, canvas_width: i32, captures: Vec<models::CaptureInfo>, layout_type: String, total_captures: i32) -> ComposeMetadata {
        ComposeMetadata {
            canvas_height,
            canvas_width,
            captures,
            layout_type,
            total_captures,
        }
    }
}

