/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeJobCreatedResponse {
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "statusUrl")]
    pub status_url: String,
}

impl ComposeJobCreatedResponse {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, job_id: String, status: String, status_url: String) -> ComposeJobCreatedResponse {
        ComposeJobCreatedResponse {
            created_at,
            job_id,
            status,
            status_url,
        }
    }
}

