/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeJobStatusResponse {
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "completedCaptures")]
    pub completed_captures: i32,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "progress")]
    pub progress: i32,
    #[serde(rename = "result", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result: Option<Option<Box<models::ComposeResponse>>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "totalCaptures")]
    pub total_captures: i32,
}

impl ComposeJobStatusResponse {
    pub fn new(completed_captures: i32, created_at: chrono::DateTime<chrono::FixedOffset>, job_id: String, progress: i32, status: String, total_captures: i32) -> ComposeJobStatusResponse {
        ComposeJobStatusResponse {
            completed_at: None,
            completed_captures,
            created_at,
            error_code: None,
            error_message: None,
            job_id,
            progress,
            result: None,
            status,
            total_captures,
        }
    }
}

