/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeOutputConfig {
    #[serde(rename = "alignment", skip_serializing_if = "Option::is_none")]
    pub alignment: Option<String>,
    #[serde(rename = "background", skip_serializing_if = "Option::is_none")]
    pub background: Option<String>,
    #[serde(rename = "border", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub border: Option<Option<Box<models::BorderConfig>>>,
    #[serde(rename = "columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Option<i32>>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "labels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Option<Box<models::LabelConfig>>>,
    #[serde(rename = "layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<Layout>,
    #[serde(rename = "maxHeight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_height: Option<Option<i32>>,
    #[serde(rename = "maxWidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_width: Option<Option<i32>>,
    #[serde(rename = "padding", skip_serializing_if = "Option::is_none")]
    pub padding: Option<i32>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<i32>,
    #[serde(rename = "shadow", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shadow: Option<Option<Box<models::ShadowConfig>>>,
    #[serde(rename = "spacing", skip_serializing_if = "Option::is_none")]
    pub spacing: Option<i32>,
    #[serde(rename = "thumbnailWidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub thumbnail_width: Option<Option<i32>>,
}

impl ComposeOutputConfig {
    pub fn new() -> ComposeOutputConfig {
        ComposeOutputConfig {
            alignment: None,
            background: None,
            border: None,
            columns: None,
            format: None,
            labels: None,
            layout: None,
            max_height: None,
            max_width: None,
            padding: None,
            quality: None,
            shadow: None,
            spacing: None,
            thumbnail_width: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Layout {
    #[serde(rename = "GRID")]
    Grid,
    #[serde(rename = "HORIZONTAL")]
    Horizontal,
    #[serde(rename = "VERTICAL")]
    Vertical,
    #[serde(rename = "MASONRY")]
    Masonry,
    #[serde(rename = "MONDRIAN")]
    Mondrian,
    #[serde(rename = "PARTITIONING")]
    Partitioning,
    #[serde(rename = "AUTO")]
    Auto,
}

impl Default for Layout {
    fn default() -> Layout {
        Self::Grid
    }
}

