/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComposeJobSummaryResponse {
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "completedCaptures")]
    pub completed_captures: i32,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "failedCaptures")]
    pub failed_captures: i32,
    #[serde(rename = "jobId")]
    pub job_id: String,
    #[serde(rename = "layoutType")]
    pub layout_type: String,
    #[serde(rename = "progress")]
    pub progress: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "totalCaptures")]
    pub total_captures: i32,
}

impl ComposeJobSummaryResponse {
    pub fn new(completed_captures: i32, created_at: chrono::DateTime<chrono::FixedOffset>, failed_captures: i32, job_id: String, layout_type: String, progress: i32, status: String, total_captures: i32) -> ComposeJobSummaryResponse {
        ComposeJobSummaryResponse {
            completed_at: None,
            completed_captures,
            created_at,
            failed_captures,
            job_id,
            layout_type,
            progress,
            status,
            total_captures,
        }
    }
}

