/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlRequest {
    #[serde(rename = "blockAds", skip_serializing_if = "Option::is_none")]
    pub block_ads: Option<bool>,
    #[serde(rename = "blockCookieBanners", skip_serializing_if = "Option::is_none")]
    pub block_cookie_banners: Option<bool>,
    #[serde(rename = "blockPopups", skip_serializing_if = "Option::is_none")]
    pub block_popups: Option<bool>,
    #[serde(rename = "crawlDelayMs", skip_serializing_if = "Option::is_none")]
    pub crawl_delay_ms: Option<i32>,
    #[serde(rename = "darkMode", skip_serializing_if = "Option::is_none")]
    pub dark_mode: Option<bool>,
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
    #[serde(rename = "excludePatterns", skip_serializing_if = "Option::is_none")]
    pub exclude_patterns: Option<Vec<String>>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "fullPage", skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    #[serde(rename = "includePatterns", skip_serializing_if = "Option::is_none")]
    pub include_patterns: Option<Vec<String>>,
    #[serde(rename = "includeSubdomains", skip_serializing_if = "Option::is_none")]
    pub include_subdomains: Option<bool>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<models::OutputSpec>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<i32>,
    #[serde(rename = "renderDelay", skip_serializing_if = "Option::is_none")]
    pub render_delay: Option<i32>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "viewport", skip_serializing_if = "Option::is_none")]
    pub viewport: Option<Box<models::ViewportConfig>>,
    #[serde(rename = "waitUntil", skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<String>,
}

impl CrawlRequest {
    pub fn new(url: String) -> CrawlRequest {
        CrawlRequest {
            block_ads: None,
            block_cookie_banners: None,
            block_popups: None,
            crawl_delay_ms: None,
            dark_mode: None,
            depth: None,
            exclude_patterns: None,
            format: None,
            full_page: None,
            include_patterns: None,
            include_subdomains: None,
            limit: None,
            outputs: None,
            quality: None,
            render_delay: None,
            timeout: None,
            url,
            viewport: None,
            wait_until: None,
        }
    }
}

