/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlPagesResponse {
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "pageSize")]
    pub page_size: i32,
    #[serde(rename = "pages")]
    pub pages: Vec<models::CrawlPageResponse>,
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "totalPages")]
    pub total_pages: i32,
}

impl CrawlPagesResponse {
    pub fn new(page: i32, page_size: i32, pages: Vec<models::CrawlPageResponse>, total: i64, total_pages: i32) -> CrawlPagesResponse {
        CrawlPagesResponse {
            page,
            page_size,
            pages,
            total,
            total_pages,
        }
    }
}

