/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlListResponse {
    #[serde(rename = "crawls")]
    pub crawls: Vec<models::CrawlResponse>,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "pageSize")]
    pub page_size: i32,
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "totalPages")]
    pub total_pages: i32,
}

impl CrawlListResponse {
    pub fn new(crawls: Vec<models::CrawlResponse>, page: i32, page_size: i32, total: i64, total_pages: i32) -> CrawlListResponse {
        CrawlListResponse {
            crawls,
            page,
            page_size,
            total,
            total_pages,
        }
    }
}

