/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlPageResponse {
    #[serde(rename = "canonicalUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub canonical_url: Option<Option<String>>,
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "contentType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "depth")]
    pub depth: i32,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "httpStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub http_status: Option<Option<i32>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "language", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language: Option<Option<String>>,
    #[serde(rename = "outputs")]
    pub outputs: Vec<models::OutputSpec>,
    #[serde(rename = "parentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<Option<String>>,
    #[serde(rename = "renderTimeMs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub render_time_ms: Option<Option<i64>>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
}

impl CrawlPageResponse {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, depth: i32, id: String, outputs: Vec<models::OutputSpec>, status: Status, url: String) -> CrawlPageResponse {
        CrawlPageResponse {
            canonical_url: None,
            completed_at: None,
            content_type: None,
            created_at,
            depth,
            description: None,
            error_code: None,
            error_message: None,
            http_status: None,
            id,
            language: None,
            outputs,
            parent_id: None,
            render_time_ms: None,
            status,
            title: None,
            url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "QUEUED")]
    Queued,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "SKIPPED")]
    Skipped,
    #[serde(rename = "CANCELLED")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}

