/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlResponse {
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "depth")]
    pub depth: i32,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "outputs")]
    pub outputs: Vec<models::OutputSpec>,
    #[serde(rename = "progress")]
    pub progress: Box<models::CrawlProgressResponse>,
    #[serde(rename = "startedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "url")]
    pub url: String,
}

impl CrawlResponse {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, depth: i32, id: String, limit: i32, outputs: Vec<models::OutputSpec>, progress: models::CrawlProgressResponse, status: Status, url: String) -> CrawlResponse {
        CrawlResponse {
            completed_at: None,
            created_at,
            depth,
            error_code: None,
            error_message: None,
            id,
            limit,
            outputs,
            progress: Box::new(progress),
            started_at: None,
            status,
            url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "QUEUED")]
    Queued,
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "PARTIALLY_COMPLETED")]
    PartiallyCompleted,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}

