/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlProgressResponse {
    #[serde(rename = "charged")]
    pub charged: i32,
    #[serde(rename = "completed")]
    pub completed: i32,
    #[serde(rename = "discovered")]
    pub discovered: i32,
    #[serde(rename = "failed")]
    pub failed: i32,
    #[serde(rename = "queued")]
    pub queued: i32,
    #[serde(rename = "skipped")]
    pub skipped: i32,
}

impl CrawlProgressResponse {
    pub fn new(charged: i32, completed: i32, discovered: i32, failed: i32, queued: i32, skipped: i32) -> CrawlProgressResponse {
        CrawlProgressResponse {
            charged,
            completed,
            discovered,
            failed,
            queued,
            skipped,
        }
    }
}

