/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrawlPageOutputResponse {
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "resultUrl")]
    pub result_url: String,
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CrawlPageOutputResponse {
    pub fn new(content_type: String, expires_at: chrono::DateTime<chrono::FixedOffset>, result_url: String, size: i64, r#type: String) -> CrawlPageOutputResponse {
        CrawlPageOutputResponse {
            content_type,
            expires_at,
            result_url,
            size,
            r#type,
        }
    }
}

