/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateScheduleRequest {
    #[serde(rename = "alertOnFailure", skip_serializing_if = "Option::is_none")]
    pub alert_on_failure: Option<bool>,
    #[serde(rename = "autoPauseAfterFailures", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auto_pause_after_failures: Option<Option<i32>>,
    #[serde(rename = "destinations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<Option<Vec<models::DeliveryDestination>>>,
    #[serde(rename = "diffThreshold", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub diff_threshold: Option<Option<f64>>,
    #[serde(rename = "endsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ends_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "onlyOnChange", skip_serializing_if = "Option::is_none")]
    pub only_on_change: Option<bool>,
    #[serde(rename = "options", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub options: Option<Option<Box<models::ScheduleScreenshotOptions>>>,
    #[serde(rename = "retentionDays", skip_serializing_if = "Option::is_none")]
    pub retention_days: Option<i32>,
    #[serde(rename = "schedule")]
    pub schedule: String,
    #[serde(rename = "startsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "webhookSecret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
    #[serde(rename = "webhookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
}

impl CreateScheduleRequest {
    pub fn new(name: String, schedule: String, url: String) -> CreateScheduleRequest {
        CreateScheduleRequest {
            alert_on_failure: None,
            auto_pause_after_failures: None,
            destinations: None,
            diff_threshold: None,
            ends_at: None,
            name,
            only_on_change: None,
            options: None,
            retention_days: None,
            schedule,
            starts_at: None,
            timezone: None,
            url,
            webhook_secret: None,
            webhook_url: None,
        }
    }
}

