/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditBalanceResponse {
    #[serde(rename = "allowanceType")]
    pub allowance_type: String,
    #[serde(rename = "balance")]
    pub balance: i32,
    #[serde(rename = "resetsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resets_at: Option<Option<String>>,
}

impl CreditBalanceResponse {
    pub fn new(allowance_type: String, balance: i32) -> CreditBalanceResponse {
        CreditBalanceResponse {
            allowance_type,
            balance,
            resets_at: None,
        }
    }
}

