/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyCaptureCountResponse {
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "date")]
    pub date: String,
}

impl DailyCaptureCountResponse {
    pub fn new(count: i64, date: String) -> DailyCaptureCountResponse {
        DailyCaptureCountResponse {
            count,
            date,
        }
    }
}

