/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DeliveryDestination {
    #[serde(rename="email")]
    Email(Box<models::EmailDestination>),
    #[serde(rename="webhook")]
    Webhook(Box<models::WebhookDestination>),
}

impl Default for DeliveryDestination {
    fn default() -> Self {
        Self::Email(Default::default())
    }
}


