/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailDestination {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "onlyOnChange", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub only_on_change: Option<Option<bool>>,
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    #[serde(rename = "to")]
    pub to: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl EmailDestination {
    pub fn new(to: Vec<String>, r#type: Type) -> EmailDestination {
        EmailDestination {
            id: None,
            only_on_change: None,
            subject: None,
            to,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "email")]
    Email,
}

impl Default for Type {
    fn default() -> Type {
        Self::Email
    }
}

