/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error")]
    pub error: Box<models::ErrorDetail>,
    #[serde(rename = "requestId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<Option<String>>,
}

impl ErrorResponse {
    pub fn new(error: models::ErrorDetail) -> ErrorResponse {
        ErrorResponse {
            error: Box::new(error),
            request_id: None,
        }
    }
}

