/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorDetail {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "documentationUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub documentation_url: Option<Option<String>>,
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorDetail {
    pub fn new(code: String, message: String) -> ErrorDetail {
        ErrorDetail {
            code,
            details: None,
            documentation_url: None,
            message,
        }
    }
}

