/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobResponse {
    #[serde(rename = "completedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "outputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Option<std::collections::HashMap<String, models::OutputInfo>>>,
    #[serde(rename = "resultUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_url: Option<Option<String>>,
    #[serde(rename = "startedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "storageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_url: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
}

impl JobResponse {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: String, status: Status, url: String) -> JobResponse {
        JobResponse {
            completed_at: None,
            created_at,
            error_code: None,
            error_message: None,
            expires_at: None,
            id,
            metadata: None,
            outputs: None,
            result_url: None,
            started_at: None,
            status,
            storage_url: None,
            url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "QUEUED")]
    Queued,
    #[serde(rename = "PROCESSING")]
    Processing,
    #[serde(rename = "COMPLETED")]
    Completed,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}

