/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonFieldSpec {
    #[serde(rename = "attribute", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attribute: Option<Option<String>>,
    #[serde(rename = "multiple", skip_serializing_if = "Option::is_none")]
    pub multiple: Option<bool>,
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl JsonFieldSpec {
    pub fn new(selector: String) -> JsonFieldSpec {
        JsonFieldSpec {
            attribute: None,
            multiple: None,
            selector,
            r#type: None,
        }
    }
}

