/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonOutputSpec {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "schema")]
    pub schema: std::collections::HashMap<String, models::JsonFieldSpec>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl JsonOutputSpec {
    pub fn new(schema: std::collections::HashMap<String, models::JsonFieldSpec>, r#type: Type) -> JsonOutputSpec {
        JsonOutputSpec {
            id: None,
            schema,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "json")]
    Json,
}

impl Default for Type {
    fn default() -> Type {
        Self::Json
    }
}

