/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LayoutPreviewResponse {
    #[serde(rename = "canvasHeight")]
    pub canvas_height: i32,
    #[serde(rename = "canvasWidth")]
    pub canvas_width: i32,
    #[serde(rename = "layout")]
    pub layout: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "placements")]
    pub placements: Vec<models::PlacementPreview>,
    #[serde(rename = "resolvedLayout")]
    pub resolved_layout: String,
}

impl LayoutPreviewResponse {
    pub fn new(canvas_height: i32, canvas_width: i32, layout: String, metadata: std::collections::HashMap<String, serde_json::Value>, placements: Vec<models::PlacementPreview>, resolved_layout: String) -> LayoutPreviewResponse {
        LayoutPreviewResponse {
            canvas_height,
            canvas_width,
            layout,
            metadata,
            placements,
            resolved_layout,
        }
    }
}

