/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkdownOutputSpec {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "mainContentOnly", skip_serializing_if = "Option::is_none")]
    pub main_content_only: Option<bool>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MarkdownOutputSpec {
    pub fn new(r#type: Type) -> MarkdownOutputSpec {
        MarkdownOutputSpec {
            id: None,
            main_content_only: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "markdown")]
    Markdown,
}

impl Default for Type {
    fn default() -> Type {
        Self::Markdown
    }
}

