/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiOutputResponse {
    #[serde(rename = "outputs")]
    pub outputs: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "renderTimeMs")]
    pub render_time_ms: i64,
    #[serde(rename = "url")]
    pub url: String,
}

impl MultiOutputResponse {
    pub fn new(outputs: std::collections::HashMap<String, serde_json::Value>, render_time_ms: i64, url: String) -> MultiOutputResponse {
        MultiOutputResponse {
            outputs,
            render_time_ms,
            url,
        }
    }
}

