/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputInfo {
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "resultUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_url: Option<Option<String>>,
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "storageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_url: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl OutputInfo {
    pub fn new(content_type: String, size: i64, r#type: String) -> OutputInfo {
        OutputInfo {
            content_type,
            result_url: None,
            size,
            storage_url: None,
            r#type,
        }
    }
}

