/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OutputSpec {
    #[serde(rename="screenshot")]
    Screenshot(Box<models::ScreenshotOutputSpec>),
    #[serde(rename="pdf")]
    Pdf(Box<models::PdfOutputSpec>),
    #[serde(rename="html")]
    Html(Box<models::HtmlOutputSpec>),
    #[serde(rename="markdown")]
    Markdown(Box<models::MarkdownOutputSpec>),
    #[serde(rename="json")]
    Json(Box<models::JsonOutputSpec>),
}

impl Default for OutputSpec {
    fn default() -> Self {
        Self::Screenshot(Default::default())
    }
}


