/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PageAction {
    #[serde(rename="click")]
    Click(Box<models::ClickAction>),
    #[serde(rename="type")]
    Type(Box<models::TypeAction>),
    #[serde(rename="press")]
    Press(Box<models::PressAction>),
    #[serde(rename="hover")]
    Hover(Box<models::HoverAction>),
    #[serde(rename="select")]
    Select(Box<models::SelectAction>),
    #[serde(rename="scroll")]
    Scroll(Box<models::ScrollAction>),
    #[serde(rename="wait")]
    Wait(Box<models::WaitAction>),
}

impl Default for PageAction {
    fn default() -> Self {
        Self::Click(Default::default())
    }
}


