/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdfOutputSpec {
    #[serde(rename = "format", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub format: Option<Option<String>>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "landscape", skip_serializing_if = "Option::is_none")]
    pub landscape: Option<bool>,
    #[serde(rename = "printBackground", skip_serializing_if = "Option::is_none")]
    pub print_background: Option<bool>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PdfOutputSpec {
    pub fn new(r#type: Type) -> PdfOutputSpec {
        PdfOutputSpec {
            format: None,
            id: None,
            landscape: None,
            print_background: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pdf")]
    Pdf,
}

impl Default for Type {
    fn default() -> Type {
        Self::Pdf
    }
}

