/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeriodUsageResponse {
    #[serde(rename = "bandwidthBytes")]
    pub bandwidth_bytes: i64,
    #[serde(rename = "bandwidthFormatted")]
    pub bandwidth_formatted: String,
    #[serde(rename = "periodEnd")]
    pub period_end: String,
    #[serde(rename = "periodStart")]
    pub period_start: String,
    #[serde(rename = "screenshotsCount")]
    pub screenshots_count: i32,
}

impl PeriodUsageResponse {
    pub fn new(bandwidth_bytes: i64, bandwidth_formatted: String, period_end: String, period_start: String, screenshots_count: i32) -> PeriodUsageResponse {
        PeriodUsageResponse {
            bandwidth_bytes,
            bandwidth_formatted,
            period_end,
            period_start,
            screenshots_count,
        }
    }
}

