/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlacementPreview {
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "width")]
    pub width: i32,
    #[serde(rename = "x")]
    pub x: i32,
    #[serde(rename = "y")]
    pub y: i32,
}

impl PlacementPreview {
    pub fn new(height: i32, index: i32, width: i32, x: i32, y: i32) -> PlacementPreview {
        PlacementPreview {
            height,
            index,
            label: None,
            width,
            x,
            y,
        }
    }
}

