/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PressAction {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "selector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Option<String>>,
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<i32>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl PressAction {
    pub fn new(key: String, r#type: Type) -> PressAction {
        PressAction {
            key,
            optional: None,
            selector: None,
            timeout: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "press")]
    Press,
}

impl Default for Type {
    fn default() -> Type {
        Self::Press
    }
}

