/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaStatusResponse {
    #[serde(rename = "bandwidth")]
    pub bandwidth: Box<models::BandwidthQuotaResponse>,
    #[serde(rename = "periodEnds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub period_ends: Option<Option<String>>,
    #[serde(rename = "screenshots")]
    pub screenshots: Box<models::QuotaDetailResponse>,
    #[serde(rename = "tier")]
    pub tier: String,
}

impl QuotaStatusResponse {
    pub fn new(bandwidth: models::BandwidthQuotaResponse, screenshots: models::QuotaDetailResponse, tier: String) -> QuotaStatusResponse {
        QuotaStatusResponse {
            bandwidth: Box::new(bandwidth),
            period_ends: None,
            screenshots: Box::new(screenshots),
            tier,
        }
    }
}

