/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaResponse {
    #[serde(rename = "bandwidth")]
    pub bandwidth: Box<models::BandwidthQuotaResponse>,
    #[serde(rename = "screenshots")]
    pub screenshots: Box<models::QuotaDetailResponse>,
}

impl QuotaResponse {
    pub fn new(bandwidth: models::BandwidthQuotaResponse, screenshots: models::QuotaDetailResponse) -> QuotaResponse {
        QuotaResponse {
            bandwidth: Box::new(bandwidth),
            screenshots: Box::new(screenshots),
        }
    }
}

