/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaDetailResponse {
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "percentUsed")]
    pub percent_used: i32,
    #[serde(rename = "remaining")]
    pub remaining: i32,
    #[serde(rename = "used")]
    pub used: i32,
}

impl QuotaDetailResponse {
    pub fn new(limit: i32, percent_used: i32, remaining: i32, used: i32) -> QuotaDetailResponse {
        QuotaDetailResponse {
            limit,
            percent_used,
            remaining,
            used,
        }
    }
}

