/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleListResponse {
    #[serde(rename = "schedules")]
    pub schedules: Vec<models::ScheduleResponse>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl ScheduleListResponse {
    pub fn new(schedules: Vec<models::ScheduleResponse>, total: i32) -> ScheduleListResponse {
        ScheduleListResponse {
            schedules,
            total,
        }
    }
}

