/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleHistoryResponse {
    #[serde(rename = "executions")]
    pub executions: Vec<models::ScheduleExecutionResponse>,
    #[serde(rename = "scheduleId")]
    pub schedule_id: String,
    #[serde(rename = "totalExecutions")]
    pub total_executions: i64,
}

impl ScheduleHistoryResponse {
    pub fn new(executions: Vec<models::ScheduleExecutionResponse>, schedule_id: String, total_executions: i64) -> ScheduleHistoryResponse {
        ScheduleHistoryResponse {
            executions,
            schedule_id,
            total_executions,
        }
    }
}

