/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleExecutionResponse {
    #[serde(rename = "changed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub changed: Option<Option<bool>>,
    #[serde(rename = "deliveries", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deliveries: Option<Option<Vec<std::collections::HashMap<String, serde_json::Value>>>>,
    #[serde(rename = "diffScore", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub diff_score: Option<Option<f64>>,
    #[serde(rename = "errorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<Option<String>>,
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "executedAt")]
    pub executed_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "fileSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<Option<i64>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "outputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "renderTimeMs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub render_time_ms: Option<Option<i64>>,
    #[serde(rename = "resultUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_url: Option<Option<String>>,
    #[serde(rename = "runId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "storageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_url: Option<Option<String>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
}

impl ScheduleExecutionResponse {
    pub fn new(executed_at: chrono::DateTime<chrono::FixedOffset>, id: String, status: String) -> ScheduleExecutionResponse {
        ScheduleExecutionResponse {
            changed: None,
            deliveries: None,
            diff_score: None,
            error_code: None,
            error_message: None,
            executed_at,
            expires_at: None,
            file_size: None,
            id,
            outputs: None,
            render_time_ms: None,
            result_url: None,
            run_id: None,
            status,
            storage_url: None,
            url: None,
        }
    }
}

