/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleResponse {
    #[serde(rename = "alertOnFailure")]
    pub alert_on_failure: bool,
    #[serde(rename = "autoPauseAfterFailures", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auto_pause_after_failures: Option<Option<i32>>,
    #[serde(rename = "consecutiveFailures")]
    pub consecutive_failures: i32,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "destinations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<Option<Vec<models::DeliveryDestination>>>,
    #[serde(rename = "diffThreshold", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub diff_threshold: Option<Option<f64>>,
    #[serde(rename = "endsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ends_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "executionCount")]
    pub execution_count: i32,
    #[serde(rename = "failureCount")]
    pub failure_count: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "lastExecutedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_executed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "nextExecutionAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_execution_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "onlyOnChange")]
    pub only_on_change: bool,
    #[serde(rename = "options", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub options: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "retentionDays")]
    pub retention_days: i32,
    #[serde(rename = "schedule")]
    pub schedule: String,
    #[serde(rename = "scheduleDescription")]
    pub schedule_description: String,
    #[serde(rename = "startsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "successCount")]
    pub success_count: i32,
    #[serde(rename = "timezone")]
    pub timezone: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "webhookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
}

impl ScheduleResponse {
    pub fn new(alert_on_failure: bool, consecutive_failures: i32, created_at: chrono::DateTime<chrono::FixedOffset>, execution_count: i32, failure_count: i32, id: String, name: String, only_on_change: bool, retention_days: i32, schedule: String, schedule_description: String, status: String, success_count: i32, timezone: String, updated_at: chrono::DateTime<chrono::FixedOffset>, url: String) -> ScheduleResponse {
        ScheduleResponse {
            alert_on_failure,
            auto_pause_after_failures: None,
            consecutive_failures,
            created_at,
            destinations: None,
            diff_threshold: None,
            ends_at: None,
            execution_count,
            failure_count,
            id,
            last_executed_at: None,
            name,
            next_execution_at: None,
            only_on_change,
            options: None,
            retention_days,
            schedule,
            schedule_description,
            starts_at: None,
            status,
            success_count,
            timezone,
            updated_at,
            url,
            webhook_url: None,
        }
    }
}

