/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotOutputSpec {
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "fullPage", skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<i32>,
    #[serde(rename = "selector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ScreenshotOutputSpec {
    pub fn new(r#type: Type) -> ScreenshotOutputSpec {
        ScreenshotOutputSpec {
            format: None,
            full_page: None,
            id: None,
            quality: None,
            selector: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "screenshot")]
    Screenshot,
}

impl Default for Type {
    fn default() -> Type {
        Self::Screenshot
    }
}

