/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotJsonResponse {
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    #[serde(rename = "encoding", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<Option<String>>,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "format")]
    pub format: String,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<i32>>,
    #[serde(rename = "renderTimeMs")]
    pub render_time_ms: i64,
    #[serde(rename = "resultUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_url: Option<Option<String>>,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "storageUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_url: Option<Option<String>>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "width")]
    pub width: i32,
}

impl ScreenshotJsonResponse {
    pub fn new(content_type: String, format: String, render_time_ms: i64, size: i32, url: String, width: i32) -> ScreenshotJsonResponse {
        ScreenshotJsonResponse {
            cached: None,
            content_type,
            data: None,
            encoding: None,
            expires_at: None,
            format,
            height: None,
            render_time_ms,
            result_url: None,
            size,
            storage_url: None,
            url,
            width,
        }
    }
}

