/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScreenshotRequest {
    #[serde(rename = "actions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Option<Vec<models::PageAction>>>,
    #[serde(rename = "blockAds", skip_serializing_if = "Option::is_none")]
    pub block_ads: Option<bool>,
    #[serde(rename = "blockCookieBanners", skip_serializing_if = "Option::is_none")]
    pub block_cookie_banners: Option<bool>,
    #[serde(rename = "blockLevel", skip_serializing_if = "Option::is_none")]
    pub block_level: Option<String>,
    #[serde(rename = "blockPopups", skip_serializing_if = "Option::is_none")]
    pub block_popups: Option<bool>,
    #[serde(rename = "customCss", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_css: Option<Option<String>>,
    #[serde(rename = "darkMode", skip_serializing_if = "Option::is_none")]
    pub dark_mode: Option<bool>,
    #[serde(rename = "delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<i32>,
    #[serde(rename = "device", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub device: Option<Option<String>>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "freezeFixed", skip_serializing_if = "Option::is_none")]
    pub freeze_fixed: Option<bool>,
    #[serde(rename = "fullPage", skip_serializing_if = "Option::is_none")]
    pub full_page: Option<bool>,
    #[serde(rename = "fullPageMode", skip_serializing_if = "Option::is_none")]
    pub full_page_mode: Option<String>,
    #[serde(rename = "hideSelectors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hide_selectors: Option<Option<Vec<String>>>,
    #[serde(rename = "maxHeight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_height: Option<Option<i32>>,
    #[serde(rename = "maxSections", skip_serializing_if = "Option::is_none")]
    pub max_sections: Option<i32>,
    #[serde(rename = "outputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Option<Vec<models::OutputSpec>>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<i32>,
    #[serde(rename = "responseType", skip_serializing_if = "Option::is_none")]
    pub response_type: Option<ResponseType>,
    #[serde(rename = "scrollInterval", skip_serializing_if = "Option::is_none")]
    pub scroll_interval: Option<i32>,
    #[serde(rename = "selector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Option<String>>,
    #[serde(rename = "session", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub session: Option<Option<Box<models::BrowserSessionRequest>>>,
    #[serde(rename = "stealthMode", skip_serializing_if = "Option::is_none")]
    pub stealth_mode: Option<bool>,
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "viewport", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub viewport: Option<Option<Box<models::ViewportConfig>>>,
    #[serde(rename = "waitFor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wait_for: Option<Option<String>>,
    #[serde(rename = "waitUntil", skip_serializing_if = "Option::is_none")]
    pub wait_until: Option<String>,
    #[serde(rename = "webhookSecret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
    #[serde(rename = "webhookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
}

impl ScreenshotRequest {
    pub fn new(url: String) -> ScreenshotRequest {
        ScreenshotRequest {
            actions: None,
            block_ads: None,
            block_cookie_banners: None,
            block_level: None,
            block_popups: None,
            custom_css: None,
            dark_mode: None,
            delay: None,
            device: None,
            format: None,
            freeze_fixed: None,
            full_page: None,
            full_page_mode: None,
            hide_selectors: None,
            max_height: None,
            max_sections: None,
            outputs: None,
            quality: None,
            response_type: None,
            scroll_interval: None,
            selector: None,
            session: None,
            stealth_mode: None,
            timeout: None,
            url,
            viewport: None,
            wait_for: None,
            wait_until: None,
            webhook_secret: None,
            webhook_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponseType {
    #[serde(rename = "BINARY")]
    Binary,
    #[serde(rename = "BASE64")]
    Base64,
    #[serde(rename = "URL")]
    Url,
}

impl Default for ResponseType {
    fn default() -> ResponseType {
        Self::Binary
    }
}

