/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScrollAction {
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "selector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Option<String>>,
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<i32>>,
    #[serde(rename = "toBottom", skip_serializing_if = "Option::is_none")]
    pub to_bottom: Option<bool>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "y", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub y: Option<Option<i32>>,
}

impl ScrollAction {
    pub fn new(r#type: Type) -> ScrollAction {
        ScrollAction {
            optional: None,
            selector: None,
            timeout: None,
            to_bottom: None,
            r#type,
            y: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "scroll")]
    Scroll,
}

impl Default for Type {
    fn default() -> Type {
        Self::Scroll
    }
}

