/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateScheduleRequest {
    #[serde(rename = "alertOnFailure", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alert_on_failure: Option<Option<bool>>,
    #[serde(rename = "autoPauseAfterFailures", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auto_pause_after_failures: Option<Option<i32>>,
    #[serde(rename = "destinations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destinations: Option<Option<Vec<models::DeliveryDestination>>>,
    #[serde(rename = "diffThreshold", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub diff_threshold: Option<Option<f64>>,
    #[serde(rename = "endsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ends_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "onlyOnChange", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub only_on_change: Option<Option<bool>>,
    #[serde(rename = "options", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub options: Option<Option<Box<models::ScheduleScreenshotOptions>>>,
    #[serde(rename = "retentionDays", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub retention_days: Option<Option<i32>>,
    #[serde(rename = "schedule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Option<String>>,
    #[serde(rename = "startsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "timezone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<Option<String>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "webhookSecret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_secret: Option<Option<String>>,
    #[serde(rename = "webhookUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<Option<String>>,
}

impl UpdateScheduleRequest {
    pub fn new() -> UpdateScheduleRequest {
        UpdateScheduleRequest {
            alert_on_failure: None,
            auto_pause_after_failures: None,
            destinations: None,
            diff_threshold: None,
            ends_at: None,
            name: None,
            only_on_change: None,
            options: None,
            retention_days: None,
            schedule: None,
            starts_at: None,
            timezone: None,
            url: None,
            webhook_secret: None,
            webhook_url: None,
        }
    }
}

