/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageResponse {
    #[serde(rename = "credits")]
    pub credits: Box<models::CreditBalanceResponse>,
    #[serde(rename = "currentPeriod")]
    pub current_period: Box<models::PeriodUsageResponse>,
    #[serde(rename = "history")]
    pub history: Vec<models::PeriodUsageResponse>,
    #[serde(rename = "organization")]
    pub organization: Box<models::UsageOrganizationResponse>,
    #[serde(rename = "quota")]
    pub quota: Box<models::QuotaResponse>,
    #[serde(rename = "tier")]
    pub tier: String,
    #[serde(rename = "totals")]
    pub totals: Box<models::TotalsResponse>,
}

impl UsageResponse {
    pub fn new(credits: models::CreditBalanceResponse, current_period: models::PeriodUsageResponse, history: Vec<models::PeriodUsageResponse>, organization: models::UsageOrganizationResponse, quota: models::QuotaResponse, tier: String, totals: models::TotalsResponse) -> UsageResponse {
        UsageResponse {
            credits: Box::new(credits),
            current_period: Box::new(current_period),
            history,
            organization: Box::new(organization),
            quota: Box::new(quota),
            tier,
            totals: Box::new(totals),
        }
    }
}

