/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ViewportConfig {
    #[serde(rename = "deviceScaleFactor", skip_serializing_if = "Option::is_none")]
    pub device_scale_factor: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl ViewportConfig {
    pub fn new() -> ViewportConfig {
        ViewportConfig {
            device_scale_factor: None,
            height: None,
            width: None,
        }
    }
}

