/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WaitAction {
    #[serde(rename = "ms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ms: Option<Option<i32>>,
    #[serde(rename = "networkIdle", skip_serializing_if = "Option::is_none")]
    pub network_idle: Option<bool>,
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "selector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selector: Option<Option<String>>,
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<i32>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl WaitAction {
    pub fn new(r#type: Type) -> WaitAction {
        WaitAction {
            ms: None,
            network_idle: None,
            optional: None,
            selector: None,
            timeout: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "wait")]
    Wait,
}

impl Default for Type {
    fn default() -> Type {
        Self::Wait
    }
}

