/*
 * Allscreenshots public API
 *
 * Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookDestination {
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<String>>,
    #[serde(rename = "onlyOnChange", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub only_on_change: Option<Option<bool>>,
    #[serde(rename = "secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secret: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "url")]
    pub url: String,
}

impl WebhookDestination {
    pub fn new(r#type: Type, url: String) -> WebhookDestination {
        WebhookDestination {
            id: None,
            only_on_change: None,
            secret: None,
            r#type,
            url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "webhook")]
    Webhook,
}

impl Default for Type {
    fn default() -> Type {
        Self::Webhook
    }
}

